var questions = {
	success: true,
	data: {
		questions: [
			{
				id: 151,
				title: "Which logic gate has one input?",
				titlePupil: "Which logic gate has one input?",
				resultDescription: null,
				answers: [
					{
						id: 538,
						forQuestionId: 151,
						forQuestion: null,
						text: "NOT",
						isCorrect: true,
						difficulty: 0.5,
						displayPos: 0,
						isDeleted: false,
						deletedOn: null,
						hiddenWord: "NOT",
					},
					{
						id: 539,
						forQuestionId: 151,
						forQuestion: null,
						text: "AND",
						isCorrect: false,
						difficulty: 0.5,
						displayPos: 0,
						isDeleted: false,
						deletedOn: null,
						hiddenWord: "AND",
					},
					{
						id: 540,
						forQuestionId: 151,
						forQuestion: null,
						text: "XAND",
						isCorrect: false,
						difficulty: 0.5,
						displayPos: 0,
						isDeleted: false,
						deletedOn: null,
						hiddenWord: "XAND",
					},
					{
						id: 541,
						forQuestionId: 151,
						forQuestion: null,
						text: "XOR",
						isCorrect: false,
						difficulty: 0.5,
						displayPos: 0,
						isDeleted: false,
						deletedOn: null,
						hiddenWord: "XOR",
					},
				],
				forConceptId: 33,
				difficulty: 0.5,
				questionType: 0,
				subTopicIds: [42],
				forSubTopicId: 42,
			},
			{
				id: 115,
				title: "If the processing speed goes up from 1GHZ to 4GHZ",
				titlePupil: "If the processing speed goes up from 1GHZ to 4GHZ",
				resultDescription: null,
				answers: [
					{
						id: 427,
						forQuestionId: 115,
						forQuestion: null,
						text: "max number of instructions executed per second is quartered",
						isCorrect: false,
						difficulty: 0.5,
						displayPos: 0,
						isDeleted: false,
						deletedOn: null,
						hiddenWord: "quartered",
					},
					{
						id: 428,
						forQuestionId: 115,
						forQuestion: null,
						text: "max number of instructions executed per second is halved",
						isCorrect: false,
						difficulty: 0.5,
						displayPos: 0,
						isDeleted: false,
						deletedOn: null,
						hiddenWord: "halved",
					},
					{
						id: 429,
						forQuestionId: 115,
						forQuestion: null,
						text: "max number of instructions executed per second doubles",
						isCorrect: false,
						difficulty: 0.5,
						displayPos: 0,
						isDeleted: false,
						deletedOn: null,
						hiddenWord: "doubles",
					},
					{
						id: 484,
						forQuestionId: 115,
						forQuestion: null,
						text: "max number of instructions executed per second quadruples",
						isCorrect: true,
						difficulty: 0.5,
						displayPos: 0,
						isDeleted: false,
						deletedOn: null,
						hiddenWord: "quadruples",
					},
				],
				forConceptId: 13,
				difficulty: 0.5,
				questionType: 0,
				subTopicIds: [6],
				forSubTopicId: 6,
			},
			{
				id: 130,
				title: "Which is the smallest of these data capacities? (4/5)",
				titlePupil: "Which is the smallest of these data capacities? (4/5)",
				resultDescription: null,
				answers: [
					{
						id: 559,
						forQuestionId: 130,
						forQuestion: null,
						text: "2 KB",
						isCorrect: true,
						difficulty: 0.5,
						displayPos: 0,
						isDeleted: false,
						deletedOn: null,
						hiddenWord: null,
					},
					{
						id: 560,
						forQuestionId: 130,
						forQuestion: null,
						text: "2049 bytes",
						isCorrect: false,
						difficulty: 0.5,
						displayPos: 0,
						isDeleted: false,
						deletedOn: null,
						hiddenWord: null,
					},
					{
						id: 561,
						forQuestionId: 130,
						forQuestion: null,
						text: "0.5 MB",
						isCorrect: false,
						difficulty: 0.5,
						displayPos: 0,
						isDeleted: false,
						deletedOn: null,
						hiddenWord: null,
					},
					{
						id: 562,
						forQuestionId: 130,
						forQuestion: null,
						text: "3 GB",
						isCorrect: false,
						difficulty: 0.5,
						displayPos: 0,
						isDeleted: false,
						deletedOn: null,
						hiddenWord: null,
					},
				],
				forConceptId: 45,
				difficulty: 0.5,
				questionType: 0,
				subTopicIds: [10],
				forSubTopicId: 10,
			},
			{
				id: 131,
				title: "Which is the largest of these data capacities?",
				titlePupil: "Which is the largest of these data capacities?",
				resultDescription: null,
				answers: [
					{
						id: 350,
						forQuestionId: 131,
						forQuestion: null,
						text: "100000 KB",
						isCorrect: false,
						difficulty: 0.5,
						displayPos: 0,
						isDeleted: false,
						deletedOn: null,
						hiddenWord: null,
					},
					{
						id: 351,
						forQuestionId: 131,
						forQuestion: null,
						text: "2048 MB",
						isCorrect: false,
						difficulty: 0.5,
						displayPos: 0,
						isDeleted: false,
						deletedOn: null,
						hiddenWord: null,
					},
					{
						id: 563,
						forQuestionId: 131,
						forQuestion: null,
						text: "2050 MB",
						isCorrect: true,
						difficulty: 0.5,
						displayPos: 0,
						isDeleted: false,
						deletedOn: null,
						hiddenWord: null,
					},
					{
						id: 585,
						forQuestionId: 131,
						forQuestion: null,
						text: "2 GB",
						isCorrect: false,
						difficulty: 0.5,
						displayPos: 0,
						isDeleted: false,
						deletedOn: null,
						hiddenWord: null,
					},
				],
				forConceptId: 45,
				difficulty: 0.5,
				questionType: 0,
				subTopicIds: [10],
				forSubTopicId: 10,
			},
			{
				id: 50,
				title:
					"Dividing tasks so that the Operating System appears to multitask is dealt with under:",
				titlePupil:
					"Dividing tasks so that the Operating System appears to multitask is dealt with under:",
				resultDescription: null,
				answers: [
					{
						id: 199,
						forQuestionId: 50,
						forQuestion: null,
						text: "Processor Management",
						isCorrect: true,
						difficulty: 0.5,
						displayPos: 0,
						isDeleted: false,
						deletedOn: null,
						hiddenWord: "Processor",
					},
					{
						id: 200,
						forQuestionId: 50,
						forQuestion: null,
						text: "Memory Management",
						isCorrect: false,
						difficulty: 0.5,
						displayPos: 0,
						isDeleted: false,
						deletedOn: null,
						hiddenWord: "Memory",
					},
					{
						id: 201,
						forQuestionId: 50,
						forQuestion: null,
						text: "File Management",
						isCorrect: false,
						difficulty: 0.5,
						displayPos: 0,
						isDeleted: false,
						deletedOn: null,
						hiddenWord: "File",
					},
					{
						id: 202,
						forQuestionId: 50,
						forQuestion: null,
						text: "Peripheral Management",
						isCorrect: false,
						difficulty: 0.5,
						displayPos: 0,
						isDeleted: false,
						deletedOn: null,
						hiddenWord: "Peripheral",
					},
				],
				forConceptId: 94,
				difficulty: 0.5,
				questionType: 0,
				subTopicIds: [30],
				forSubTopicId: 30,
			},
		],
		userSubTopics: [
			{
				forSubTopicId: 6,
				knowledgeLevel: 0.031216135,
				knowledgeChange: 0,
			},
		],
	},
};
